services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      POSTGRES_DB: $pg_name
      POSTGRES_USER: $pg_user
      POSTGRES_PASSWORD: $pg_pass
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$pg_user", "-d", "$pg_name" ]
      interval: 5s
      timeout: 2s
      retries: 10

  adminer:
    image: adminer
    ports:
      - 8080:8080
